const initialState = {
  headerTitle: '',
  drugListOneTabBarIndex: 0,
  subCategoryList: [],
  drugListForThree: [],
  drugFormList: {},
  drugType: {},
  drugListByName: [],
  drugList: {},
  diseaseListOne: [],
  diseaseListTwo: [],
  diseaseListThree: [],
  diseaseListByName: [],
  diseaseList: [],
  searchList: [],
  interactDetail: {},
  towInteract: [],
  interactDrugList: [],
  drugListForSearch: [],
  pharmaceuticalListForSearch: [],
  catalogForPharmaceuticalForSearch: [],
  catalogForDrugCategoryForSearch: [],
  catalogForChineseMedicineForSearch: [],
  isShowHistoryForSearch: true,
  searchingHistoryListForSearch: [],
  handleTestPending: false,
  handleTestError: null,
  confirmedIndicationListForSearch: [],
  relatedIndicationListForSearch: [],
  isShowSearchDrugForSearch: false,
  isShowCanSearchDrugForSearch: false,
  allowInsertUserInfoForSearch: false,
  drugListByOTCTabBarIndex: 0,
  drugListByOTC: [],
  lastInputMsg: '',
  isShowLoading: false,
  isEndPage: false,
  relatedIndicationListSplice: [],
  currPageIndexForSearch: 0,
  shiYingZhengForSearch: [],
  pageTitleMap: {},
  diseaseTypeListPageProps: [],
  appConfig: {},
  interactData: {},
  allowListLoading: false,
  drugListTowTabBarIndex: 0,
  isShowChoosePreciseDisease: false,
  drugCheckSelectDrugList: [],
  choosePreciseDiseaseListForSearch: [],
  isShowYesBtnForDrugBadgeComp: true,
  isShowHistoryForDrugBadge: false,
  searchingHistoryListForDrugBadge: [],
  allowInsertUserInfoForDrugBadge: false,
  pharmaceuticalListForDrugBadge: [],
  drugListForDrugBadge: [],
  selectDrugForDrugBadge: [],
  userInfoForDrugBadge: {},
  allowShowBtnGroupForDrugBadge: false,
  isShowInteractResult: false,
  isShowContraindication: false,
  interactResultForDrugBadge: [],
  contraindicationForDrugBadge: [],
  isShowDrugListForDrugBadge: false,
  showDrugListByOTC: false,
  ShowDrugInteractionNothing: false,
  ShowDrugInteractionHistory: true,
  catalogForPharmaceuticalForDrugBadge:[],

  // -------- 辅助问诊state ----------
  d3RawData: {},
  d3Data: {
    links: [],
    nodes: [],
  },
  // -------- ---------- ----------

  treeData: [],
};

export default initialState;
